"""report_chunks for RAG

Revision ID: 7e027418991b
Revises: ae0ce6544f46
Create Date: 2026-07-14 13:48:19.372898
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "7e027418991b"
down_revision: str | None = "ae0ce6544f46"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_chunks",
        sa.Column("chunk_id", sa.String(length=30), nullable=False),
        sa.Column("report_id", sa.String(length=30), nullable=False),
        sa.Column("ticker_symbol", sa.String(length=12), nullable=True),
        sa.Column("section", sa.String(length=80), nullable=True),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "embedding",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("embed_model", sa.String(length=60), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.report_id"],
            name=op.f("fk_report_chunks_report_id_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("chunk_id", name=op.f("pk_report_chunks")),
        sa.UniqueConstraint("report_id", "seq", name=op.f("uq_report_chunks_report_id")),
    )
    with op.batch_alter_table("report_chunks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_report_chunks_report_id"), ["report_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_report_chunks_ticker_symbol"), ["ticker_symbol"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report_chunks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_report_chunks_ticker_symbol"))
        batch_op.drop_index(batch_op.f("ix_report_chunks_report_id"))

    op.drop_table("report_chunks")
    # ### end Alembic commands ###
