"""quant tables: fundamentals, index defs/scores, weight profiles, composites, backtests

Revision ID: 8aed69a3c7d7
Revises: 7e027418991b
Create Date: 2026-07-15 15:00:13.185688
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "8aed69a3c7d7"
down_revision: str | None = "7e027418991b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "index_definitions",
        sa.Column("index_key", sa.String(length=30), nullable=False),
        sa.Column("version", sa.String(length=10), nullable=False),
        sa.Column("direction", sa.String(length=15), nullable=False),
        sa.Column(
            "params",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "direction IN ('higher_better','lower_better')",
            name=op.f("ck_index_definitions_direction"),
        ),
        sa.PrimaryKeyConstraint("index_key", name=op.f("pk_index_definitions")),
    )
    op.create_table(
        "weight_profiles",
        sa.Column("profile_id", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column(
            "weights",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("profile_id", name=op.f("pk_weight_profiles")),
        sa.UniqueConstraint("name", name=op.f("uq_weight_profiles_name")),
    )
    op.create_table(
        "backtest_runs",
        sa.Column("backtest_id", sa.String(length=30), nullable=False),
        sa.Column("profile_id", sa.String(length=30), nullable=False),
        sa.Column("from_date", sa.Date(), nullable=False),
        sa.Column("to_date", sa.Date(), nullable=False),
        sa.Column(
            "universe",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("rebalance", sa.String(length=10), nullable=False),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("snapshot_id", sa.String(length=80), nullable=False),
        sa.Column("code_version", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column(
            "metrics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("artifact_path", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued','running','done','failed')", name=op.f("ck_backtest_runs_status")
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["weight_profiles.profile_id"],
            name=op.f("fk_backtest_runs_profile_id_weight_profiles"),
        ),
        sa.PrimaryKeyConstraint("backtest_id", name=op.f("pk_backtest_runs")),
    )
    op.create_table(
        "composite_scores",
        sa.Column("ticker_id", sa.String(length=30), nullable=False),
        sa.Column("profile_id", sa.String(length=30), nullable=False),
        sa.Column("score_date", sa.Date(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["weight_profiles.profile_id"],
            name=op.f("fk_composite_scores_profile_id_weight_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["ticker_id"], ["tickers.ticker_id"], name=op.f("fk_composite_scores_ticker_id_tickers")
        ),
        sa.PrimaryKeyConstraint(
            "ticker_id", "profile_id", "score_date", name=op.f("pk_composite_scores")
        ),
    )
    op.create_table(
        "fundamentals",
        sa.Column("ticker_id", sa.String(length=30), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column(
            "metrics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("snapshot_id", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticker_id"], ["tickers.ticker_id"], name=op.f("fk_fundamentals_ticker_id_tickers")
        ),
        sa.PrimaryKeyConstraint("ticker_id", "as_of", name=op.f("pk_fundamentals")),
    )
    op.create_table(
        "index_scores",
        sa.Column("ticker_id", sa.String(length=30), nullable=False),
        sa.Column("index_key", sa.String(length=30), nullable=False),
        sa.Column("score_date", sa.Date(), nullable=False),
        sa.Column("raw_value", sa.Float(), nullable=True),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("inputs_digest", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["index_key"],
            ["index_definitions.index_key"],
            name=op.f("fk_index_scores_index_key_index_definitions"),
        ),
        sa.ForeignKeyConstraint(
            ["ticker_id"], ["tickers.ticker_id"], name=op.f("fk_index_scores_ticker_id_tickers")
        ),
        sa.PrimaryKeyConstraint(
            "ticker_id", "index_key", "score_date", name=op.f("pk_index_scores")
        ),
    )
    with op.batch_alter_table("index_scores", schema=None) as batch_op:
        batch_op.create_index("ix_index_scores_date", ["score_date", "index_key"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("index_scores", schema=None) as batch_op:
        batch_op.drop_index("ix_index_scores_date")

    op.drop_table("index_scores")
    op.drop_table("fundamentals")
    op.drop_table("composite_scores")
    op.drop_table("backtest_runs")
    op.drop_table("weight_profiles")
    op.drop_table("index_definitions")
    # ### end Alembic commands ###
