"""initial schema: phase-1 tables + dormant billing

Revision ID: ae0ce6544f46
Revises:
Create Date: 2026-07-11 15:23:29.215107
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ae0ce6544f46"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("agent_id", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("default_model", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('cloud','local','human')", name=op.f("ck_agents_kind")),
        sa.PrimaryKeyConstraint("agent_id", name=op.f("pk_agents")),
        sa.UniqueConstraint("name", name=op.f("uq_agents_name")),
    )
    op.create_table(
        "audit_events",
        sa.Column("event_id", sa.String(length=30), nullable=False),
        sa.Column("actor_kind", sa.String(length=10), nullable=False),
        sa.Column("actor_id", sa.String(length=100), nullable=True),
        sa.Column("run_id", sa.String(length=30), nullable=True),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=True),
        sa.Column("entity_id", sa.String(length=30), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_audit_events")),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_at"), ["at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_entity_id"), ["entity_id"], unique=False)

    op.create_table(
        "idempotency_keys",
        sa.Column("idem_key", sa.String(length=200), nullable=False),
        sa.Column("key_id", sa.String(length=30), nullable=False),
        sa.Column("request_hash", sa.String(length=80), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column(
            "response_body",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("idem_key", "key_id", name=op.f("pk_idempotency_keys")),
    )
    op.create_table(
        "jobs",
        sa.Column("job_id", sa.String(length=30), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("run_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=60), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued','running','done','failed')", name=op.f("ck_jobs_status")
        ),
        sa.PrimaryKeyConstraint("job_id", name=op.f("pk_jobs")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_status"), ["status"], unique=False)

    op.create_table(
        "stripe_events",
        sa.Column("stripe_event_id", sa.String(length=80), nullable=False),
        sa.Column("type", sa.String(length=60), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("stripe_event_id", name=op.f("pk_stripe_events")),
    )
    op.create_table(
        "subscribers",
        sa.Column("subscriber_id", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("subscriber_id", name=op.f("pk_subscribers")),
        sa.UniqueConstraint("email", name=op.f("uq_subscribers_email")),
        sa.UniqueConstraint("stripe_customer_id", name=op.f("uq_subscribers_stripe_customer_id")),
    )
    op.create_table(
        "tickers",
        sa.Column("ticker_id", sa.String(length=30), nullable=False),
        sa.Column("symbol", sa.String(length=12), nullable=False),
        sa.Column("exchange", sa.String(length=12), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("sector", sa.String(length=64), nullable=True),
        sa.Column("industry", sa.String(length=64), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "meta",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("ticker_id", name=op.f("pk_tickers")),
        sa.UniqueConstraint("symbol", "exchange", name=op.f("uq_tickers_symbol")),
    )
    op.create_table(
        "agent_runs",
        sa.Column("run_id", sa.String(length=30), nullable=False),
        sa.Column("agent_id", sa.String(length=30), nullable=False),
        sa.Column("task", sa.String(length=200), nullable=False),
        sa.Column("input_digest", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("tokens_used", sa.BigInteger(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('running','succeeded','failed','abandoned')",
            name=op.f("ck_agent_runs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.agent_id"], name=op.f("fk_agent_runs_agent_id_agents")
        ),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_agent_runs")),
    )
    op.create_table(
        "api_keys",
        sa.Column("key_id", sa.String(length=30), nullable=False),
        sa.Column("agent_id", sa.String(length=30), nullable=False),
        sa.Column("key_prefix", sa.String(length=20), nullable=False),
        sa.Column("key_hash", sa.String(length=200), nullable=False),
        sa.Column(
            "scopes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.agent_id"], name=op.f("fk_api_keys_agent_id_agents")
        ),
        sa.PrimaryKeyConstraint("key_id", name=op.f("pk_api_keys")),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_keys_key_prefix"), ["key_prefix"], unique=False)

    op.create_table(
        "entitlements",
        sa.Column("subscriber_id", sa.String(length=30), nullable=False),
        sa.Column("feature", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscriber_id"],
            ["subscribers.subscriber_id"],
            name=op.f("fk_entitlements_subscriber_id_subscribers"),
        ),
        sa.PrimaryKeyConstraint("subscriber_id", "feature", name=op.f("pk_entitlements")),
    )
    op.create_table(
        "price_bars",
        sa.Column("ticker_id", sa.String(length=30), nullable=False),
        sa.Column("bar_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("high", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("low", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("close", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("adj_close", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("snapshot_id", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticker_id"], ["tickers.ticker_id"], name=op.f("fk_price_bars_ticker_id_tickers")
        ),
        sa.PrimaryKeyConstraint("ticker_id", "bar_date", name=op.f("pk_price_bars")),
    )
    op.create_table(
        "subscriptions",
        sa.Column("subscription_id", sa.String(length=30), nullable=False),
        sa.Column("subscriber_id", sa.String(length=30), nullable=False),
        sa.Column("stripe_subscription_id", sa.String(length=80), nullable=False),
        sa.Column("tier", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("tier IN ('free','pro','quant')", name=op.f("ck_subscriptions_tier")),
        sa.ForeignKeyConstraint(
            ["subscriber_id"],
            ["subscribers.subscriber_id"],
            name=op.f("fk_subscriptions_subscriber_id_subscribers"),
        ),
        sa.PrimaryKeyConstraint("subscription_id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint(
            "stripe_subscription_id", name=op.f("uq_subscriptions_stripe_subscription_id")
        ),
    )
    op.create_table(
        "reports",
        sa.Column("report_id", sa.String(length=30), nullable=False),
        sa.Column("ticker_id", sa.String(length=30), nullable=True),
        sa.Column("sector", sa.String(length=64), nullable=True),
        sa.Column("report_type", sa.String(length=40), nullable=False),
        sa.Column("schema_version", sa.String(length=10), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("author_agent_id", sa.String(length=30), nullable=False),
        sa.Column("author_model", sa.String(length=100), nullable=True),
        sa.Column("agent_run_id", sa.String(length=30), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column(
            "verdict",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "body",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("supersedes_report_id", sa.String(length=30), nullable=True),
        sa.Column("reviewed_by", sa.String(length=100), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft','submitted','approved','published','rejected')",
            name=op.f("ck_reports_status"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"], ["agent_runs.run_id"], name=op.f("fk_reports_agent_run_id_agent_runs")
        ),
        sa.ForeignKeyConstraint(
            ["author_agent_id"], ["agents.agent_id"], name=op.f("fk_reports_author_agent_id_agents")
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_report_id"],
            ["reports.report_id"],
            name=op.f("fk_reports_supersedes_report_id_reports"),
        ),
        sa.ForeignKeyConstraint(
            ["ticker_id"], ["tickers.ticker_id"], name=op.f("fk_reports_ticker_id_tickers")
        ),
        sa.PrimaryKeyConstraint("report_id", name=op.f("pk_reports")),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index("ix_reports_author", ["author_agent_id", "created_at"], unique=False)
        batch_op.create_index(
            "ix_reports_ticker_status", ["ticker_id", "status", "created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index("ix_reports_ticker_status")
        batch_op.drop_index("ix_reports_author")

    op.drop_table("reports")
    op.drop_table("subscriptions")
    op.drop_table("price_bars")
    op.drop_table("entitlements")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_keys_key_prefix"))

    op.drop_table("api_keys")
    op.drop_table("agent_runs")
    op.drop_table("tickers")
    op.drop_table("subscribers")
    op.drop_table("stripe_events")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_jobs_kind"))

    op.drop_table("jobs")
    op.drop_table("idempotency_keys")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_entity_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_at"))
        batch_op.drop_index(batch_op.f("ix_audit_events_action"))

    op.drop_table("audit_events")
    op.drop_table("agents")
    # ### end Alembic commands ###
