"""news, filings, schedules, alerts (ADR-0002)

Revision ID: c5b6157daadf
Revises: 8aed69a3c7d7
Create Date: 2026-07-15 16:03:14.635635
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c5b6157daadf"
down_revision: str | None = "8aed69a3c7d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedules",
        sa.Column("schedule_id", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("job_kind", sa.String(length=40), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("interval_minutes", sa.Integer(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("last_enqueued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("schedule_id", name=op.f("pk_schedules")),
        sa.UniqueConstraint("name", name=op.f("uq_schedules_name")),
    )
    with op.batch_alter_table("schedules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_schedules_next_run_at"), ["next_run_at"], unique=False)

    op.create_table(
        "alerts",
        sa.Column("alert_id", sa.String(length=30), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("ticker_id", sa.String(length=30), nullable=True),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("dedupe_key", sa.String(length=120), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("severity IN ('info','warn','high')", name=op.f("ck_alerts_severity")),
        sa.ForeignKeyConstraint(
            ["ticker_id"], ["tickers.ticker_id"], name=op.f("fk_alerts_ticker_id_tickers")
        ),
        sa.PrimaryKeyConstraint("alert_id", name=op.f("pk_alerts")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_alerts_dedupe_key")),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_alerts_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_ticker_id"), ["ticker_id"], unique=False)

    op.create_table(
        "filings",
        sa.Column("accession_no", sa.String(length=30), nullable=False),
        sa.Column("ticker_id", sa.String(length=30), nullable=False),
        sa.Column("form_type", sa.String(length=20), nullable=False),
        sa.Column("filed_at", sa.Date(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("is_important", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticker_id"], ["tickers.ticker_id"], name=op.f("fk_filings_ticker_id_tickers")
        ),
        sa.PrimaryKeyConstraint("accession_no", name=op.f("pk_filings")),
    )
    with op.batch_alter_table("filings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_filings_filed_at"), ["filed_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_filings_form_type"), ["form_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_filings_ticker_id"), ["ticker_id"], unique=False)

    op.create_table(
        "news_items",
        sa.Column("news_id", sa.String(length=30), nullable=False),
        sa.Column("ticker_id", sa.String(length=30), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=1000), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("content_hash", sa.String(length=80), nullable=False),
        sa.Column("sentiment", sa.Float(), nullable=True),
        sa.Column("relevance", sa.Float(), nullable=True),
        sa.Column("analyzed_by", sa.String(length=100), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticker_id"], ["tickers.ticker_id"], name=op.f("fk_news_items_ticker_id_tickers")
        ),
        sa.PrimaryKeyConstraint("news_id", name=op.f("pk_news_items")),
        sa.UniqueConstraint("content_hash", name=op.f("uq_news_items_content_hash")),
    )
    with op.batch_alter_table("news_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_news_items_published_at"), ["published_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_news_items_ticker_id"), ["ticker_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("news_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_news_items_ticker_id"))
        batch_op.drop_index(batch_op.f("ix_news_items_published_at"))

    op.drop_table("news_items")
    with op.batch_alter_table("filings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_filings_ticker_id"))
        batch_op.drop_index(batch_op.f("ix_filings_form_type"))
        batch_op.drop_index(batch_op.f("ix_filings_filed_at"))

    op.drop_table("filings")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_ticker_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_kind"))

    op.drop_table("alerts")
    with op.batch_alter_table("schedules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_schedules_next_run_at"))

    op.drop_table("schedules")
    # ### end Alembic commands ###
